### ISSUE TITLE
Crashes Mac OS X Mavericks

### ISSUE THREAD

**Issue by voronianski** [bdelliott/sshpass#2]
Not sure that only `sshpass` is the cause but take a look on the details - https://github.com/ansible/ansible/issues/5007#issuecomment-48891219

**Comment by th48ad** [comment]
There seems to be some race condition when sshpass is abruptly killed via ctrl-c or SIGKILL/SIGTERM which causes a kernel panic in MacOS. Pretty crappy that a userspace application could trigger that in the kernel.. Anyhow I have a patch (really a workaround) for sshpass if you're willing to re-compile from source:

https://gist.github.com/th48ad/276f39ac3cb20f464919

**Comment by bdelliott** [comment]
Hi, you have the wrong project.  The sshpass you want is on sourceforge.
